services:
  lms.api:
    container_name: LMS-app
    image: ${DOCKER_REGISTRY-}lmsapi
    build:
      context: .
      dockerfile: LMS.API/Dockerfile
    ports:
        - "5000:5000"
        - "5001:5001"
    depends_on:
        - db
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=M@tkh4umo1
    ports:
      - "1433:1433" 
    volumes:
      - sql_data:/var/opt/mssql
volumes:
  sql_data: 