services:
  code-executor:
    build: .
    container_name: code-executor
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MAX_MEMORY=512m
      - TIMEOUT_SECONDS=5
    mem_limit: 1g